### PR TITLE
Added links for quizes

### PR DESCRIPTION
**Pull request by linx5o**
Added links for 3.1, 3.2, 3.3
Assignments still missing as not visible on quercus

Links are present for 3.4, 3.5, 3.6 but clicking on them results in Access Denied

### CODE REVIEW

**Comment by linx5o** [comment]
The knowledge check for the orientation modules also has no place, even in Course 1 it is not listed on the course site. Potential to add it in to the course site. Can only be accessed through Quercus right now.

**Comment by linx5o** [comment]
image
Multiple duplicate files @sgbaird

**Comment by linx5o** [comment]
Missing links for 3.0 Orientation, 3.1, 3.2, 3.3 Assignments and their Quercus assignments.

**Review by sgbaird — APPROVED** [review]
All looks good to me!

**Pull request merged**
